### ISSUE TITLE
[Feature Request] Dont include nulls option

### ISSUE THREAD

**Issue by therealcarnivor** [fratsloos/fr24_card#10]
![Capture](https://user-images.githubusercontent.com/46380907/175935642-f76c6a87-0012-41b7-89a5-461aee9e5c7f.PNG)

Option to not include blank entries?

I have a top 10 furthest aircraft card, but the aircraft that have no distance recorded are included, would it be possible to have a configuration to toggle if these should be included or not.

**Comment by fratsloos** [comment]
This will be available in the next release.
