### ISSUE TITLE
Adding a column for Aircraft Type?

### ISSUE THREAD

**Issue by tejasitraj** [fratsloos/fr24_card#15]
Hi! First off - great card, really appreciate the work you have put in :)

I use the aircraft.json output of the [tar1090 docker container](https://hub.docker.com/r/mikenye/tar1090), which has an option for outputting the aircraft type (B737, A320 etc) as well.
I wonder if you would be willing to add the option into your card, to include the Aircraft type column if available?

**Comment by fratsloos** [comment]
Can you upload the output of your `aircraft.json`?

**Comment by tejasitraj** [comment]
[aircraft.txt](https://github.com/fratsloos/fr24_card/files/9331140/aircraft.txt)

Here it is! I saved it as a txt as the site didnt allow me to upload the json file. Thanks!

**Comment by fratsloos** [comment]
Thanks @tejasitraj! I see your JSON also contains the registration of the aircraft. I'll use that as well, with a fallback to the current method.

**Comment by tejasitraj** [comment]
@fratsloos wow thank you!! Really appreciate the responsiveness. 
I have temporarily made a markdown card, to show the table - while I hope to switch back to your card if you update it :) 

![Screenshot_20220814-104735_Home Assistant](https://user-images.githubusercontent.com/14822776/184529553-e49205c4-d247-4f2f-ad4b-68d05298e18e.jpg)

**Comment by fratsloos** [comment]
I've released v0.5.2 with a fix for this issue.

**Comment by mpjanofsky** [comment]
I'm not seeing the aircraft type in my aircraft.json - I'm not seeing any options to have it appear using [docker-fr24feed-piaware-dump1090](https://github.com/Thom-x/docker-fr24feed-piaware-dump1090). Can you point me in the right direction for that?

**Comment by tejasitraj** [comment]
@mpjanofsky as far as I know, only tar1090 provides the aircraft type in its aircraft.json output. See link in the original post above.

**Comment by mpjanofsky** [comment]
@tejasitraj That makes sense - I'll have to look at running tar1090 instead, I think I missed that part. Thanks
