### ISSUE TITLE
Altitude and Speed not reported in card

### ISSUE THREAD

**Issue by caphector** [fratsloos/fr24_card#2]
**Describe the bug**
Card not reporting Speed / Altitude

**To Reproduce**

1. Set up HA, 1090 and other assorted services
1. Validate that 1090 shows speed/altitude data in GUI
1. Verify that JSON output contains what appears to be altitude and speed data:
```
{"hex":"a52c35","type":"adsb_icao","flight":"N432T   ","alt_baro":1175,"alt_geom":1200,"gs":130.3,"track":194.68,"baro_rate":0,"category":"A1","nav_qnh":1016.8,"nav_altitude_mcp":1216,"lat":37.575027,"lon":-122.087675,"nic":8,"rc":186,"seen_pos":50.829,"r_dst":4.994,"r_dir":276.8,"version":0,"nic_baro":1,"nac_p":10,"nac_v":2,"sil":3,"sil_type":"unknown","alert":0,"spi":0,"mlat":[],"tisb":[],"messages":12,"seen":50.6,"rssi":-31.8},
```

**Screenshots**
<img width="232" alt="Tar1090" src="https://user-images.githubusercontent.com/8420750/174666385-a1503649-2040-41f6-be5a-a9bc06e6f83e.png">
<img width="428" alt="Home Assistant" src="https://user-images.githubusercontent.com/8420750/174666460-cd32db29-0c25-45a0-818e-ed170c270ee9.png">

**Environment (please complete the following information):**
 - Home Assistant version: 2022.6.6

**Additional context**

**Comment by sarahmva** [comment]
I see the same issue. I wonder if there are different json attributes for different dump1090 versions. 
`{"hex":"abad6c","flight":"SWA1093 ","alt_baro":25950,"alt_geom":27375,"gs":414.3,"ias":282,"tas":428,"mach":0.700,"track":72.4,"track_rate":0.00,"roll":-0.2,"mag_heading":76.5,"baro_rate":-2112,"geom_rate":-2368,"squawk":"2523","emergency":"none","category":"A3","nav_qnh":1013.6,"nav_altitude_mcp":6016,"nav_altitude_fms":19008,"nav_heading":71.7,"lat":38.543335,"lon":-78.259735,"nic":7,"rc":371,"seen_pos":0.5,"version":2,"nic_baro":1,"nac_p":8,"nac_v":1,"sil":3,"sil_type":"perhour","gva":1,"sda":2,"mlat":[],"tisb":[],"messages":991,"seen":0.5,"rssi":-12.3},
`
looking through the json data, I see "alt_geom" as altitude and "gs" as ground speed (I assume). Looking through the constructor in the code, it seems to be using "altitude" and "speed" as attribute names (I may be wrong).

**Comment by sarahmva** [comment]
seems there are too many different forks of dump1090 around. If I understand the flightradar24 github correctly, then they use their own fork of dump1090 with values based on an older specification. Some of the other forks use different attributes:

current versions of dump1090 use
alt_baro: the aircraft barometric altitude in feet
alt_geom: geometric (GNSS / INS) altitude in feet referenced to the WGS84 ellipsoid
gs: ground speed in knots.

@caphector : is your system built from an original flighradar24 image? I use a piaware based system and hence have a different dump1090, seems like your dump1090 is the same than mine when it comes to the json attributes.

**Comment by fratsloos** [comment]
Yes, I was informed of that in a [topic on the Home Assistant Community](https://community.home-assistant.io/t/flightradar24-as-an-add-on/75081/51). It looks like your JSON is from tar1090? I've only tested with Dump1090 (from Flightradar24), which is different.

I'll take a look to get this sorted. Compared to the older specification used by Flightradar24, should I use `alt_baro` or `alt_geom`?

**Comment by sarahmva** [comment]
Thanks @fratsloos! based on my comparison between json and the display of my feeder, it is showing alt_baro.

**Comment by RandomFunctionForUsername** [comment]
> Thanks @fratsloos! based on my comparison between json and the display of my feeder, it is showing alt_baro.

I have the same json response with alt_baro, can you tell me what you did to fix this?

**Comment by fratsloos** [comment]
@sarahmva Thx, I'll use `alt_baro`.
@RandomFunctionForUsername There is no fix yet, I'll work on it as soon as possible.

**Comment by fratsloos** [comment]
Version 0.3.0 is available in HACS which solves this issue.

**Comment by sarahmva** [comment]
Fantastic, thank you. It is now working!

**Comment by caphector** [comment]
Also confirmed as working; thanks!
