### ISSUE TITLE
Icon color based on altitude

### ISSUE THREAD

**Issue by therealhalifax** [fratsloos/fr24_card#20]
**Is your feature request related to a problem? Please describe.**
The colors of the Icons based on the hex Code is very confusing and gives no information. 

**Describe the solution you'd like**
Add an Option to change the color of the Icons based on the altitude for example. Same color the addon is using. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by fratsloos** [comment]
Hi @therealhalifax, thank you for the feedback. I'll take this request in account when I'm done with other changes I want to implement. I'm not totally sure what you mean with the following:
> Same color the addon is using.

**Comment by therealhalifax** [comment]
@fratsloos I mean in the Addon on the map the Icons of the planes have a color according to it's altitude. And it would be great to have the same color here.

**Comment by fratsloos** [comment]
Today I released version 1.0.0-alpha. This release includes changes for this request. If you want to test the feature, please see the [release](https://github.com/fratsloos/fr24_card/releases/tag/v1.0.0-alpha). To use this feature, the card config needs to be updated, see the [readme](https://github.com/fratsloos/fr24_card/blob/v1.0.0-alpha/readme.md) for more information.

The card can be tested by enabling the option 'Show beta versions' when (re)downloading the card in HACS. Issues with the release can be reported in the issue tracker.

**Comment by therealhalifax** [comment]
@fratsloos thank you very much. its work fine and as expected! great work!

**Comment by fratsloos** [comment]
Yeah, I really like the change :)
