### ISSUE TITLE
Add elevation angle above the horizon to columns 

### ISSUE THREAD

**Issue by Roofcatbusy** [fratsloos/fr24_card#5]
Hello, nice card! congratulations and thanks for your efforts. It would be nice if it is possible to add another column, which shows elevation angle (angle between horizon and aircraft)  for a given aircraft. I often wonder how high (low) above the horizon is the arcraft and making trig on the fly is a bit difficult.

Regards,
Alexey

**Comment by fratsloos** [comment]
Hi Alexey, thanks for your comment! I'm wondering if you have any information about how to calculate the angle?

**Comment by Roofcatbusy** [comment]
Sorry for delay with the answer, in first approximation one can calculate elevation angle as arcTangens ( height/distance) 

BTW, another idea for improvement of your great card is developing separate "sensor" for  reading number of planes "visible" by dump1090. As I understand it may be found in `status.json `file aside of `aircraft.json `which you already use. If you prefer I can open separate issue for that.
Regards
Alexey
