### ISSUE TITLE
[Feature Request] Optional Title

### ISSUE THREAD

**Issue by therealcarnivor** [fratsloos/fr24_card#7]
To help sort multiple instances of the same card with different sort criteria, an option to add a title

**Comment by fratsloos** [comment]
You mean something like this?

![Screenshot 2022-06-26 at 15 00 32](https://user-images.githubusercontent.com/9197177/175815404-e791af82-b70d-405a-93b2-0a7b4e961e46.png)

**Comment by therealcarnivor** [comment]
My Bads, i should read before i get over excited

**Comment by fratsloos** [comment]
> My Bads, i should read before i get over excited

Well, I guess it's not in the documentation. The title is not added by the plugin, but it's a default property of HA.
