### ISSUE TITLE
Configurable table head colors (both background and text)

### ISSUE THREAD

**Issue by AdmiralStipe** [fratsloos/fr24_card#9]
In my theme the text in the head of the table is not clearly visible due to theme color selection. 

If possible, make the table head background color and table head text color configurable in the card settings instead of adopting the main theme color scheme.  

Tried to achieve that with `card_mod: ' option, but didn't succeed.

**Comment by AdmiralStipe** [comment]
Not sure if I expressed myself clearly... with my request I meant configurable table head colors on the main card (as I can see, you are adding it to popup - or is this just the start and you will also do the main table later?). 
Surely, the problem is the same on popup, but my main issue was the main table on the card directly (as it is always visible in frontend).

**Comment by fratsloos** [comment]
@AdmiralStipe I'm not done yet, this is only the first commit on the issue.

**Comment by AdmiralStipe** [comment]
Tested the develop branch, works great. Thx a lot :) .

**Comment by fratsloos** [comment]
Very good. It will be in a release real soon.
